// AUTOGENERATED
// hash:1743151799
// prefab:Assets/1DEBUG/Image.prefab
// guid:52fd1dcd03e55da478f76d0edb4e7a61
// localId:2832314818892033150
// transform:Image
#pragma warning disable IDE1006
namespace GFSYS.AutoGenerated.ValueKeys
{
    public static class ImageKeys
    {
        // Bool False
        public const string a1 = "a1";

        // Bool False
        public const string b1 = "b1";

        // Int 10
        public const string t = "t";
    }
}
